version: '3.7'
services:
  aktin-client:
    build:
      context: ../..
      dockerfile: docker/aktin-client/Dockerfile
    environment:
      BROKER_REQUEST_MEDIATYPE: ${BROKER_REQUEST_MEDIATYPE:-text}
      BROKER_RESULT_MEDIATYPE: ${BROKER_RESULT_MEDIATYPE:-application/json}
      BROKER_ENDPOINT_URI: ${BROKER_ENDPOINT_URI:-http://aktin-broker:8080/broker/}
      CLIENT_AUTH_CLASS: ${CLIENT_AUTH_CLASS:-org.aktin.broker.client2.auth.ApiKeyAuthentication}
      CLIENT_AUTH_PARAM: ${CLIENT_AUTH_PARAM:-xxxApiKey123}
      CLIENT_WEBSOCKET_PING_SECONDS: ${CLIENT_WEBSOCKET_PING_SECONDS:-600}
      CLIENT_WEBSOCKET_RECONNECT_SECONDS: ${CLIENT_WEBSOCKET_RECONNECT_SECONDS:-10}
      CLIENT_WEBSOCKET_RECONNECT_POLLING: ${CLIENT_WEBSOCKET_RECONNECT_POLLING:-true}
      PROCESS_TIMEOUT_SECONDS: ${PROCESS_TIMEOUT_SECONDS:-60}
      PROCESS_COMMAND: ${PROCESS_COMMAND:-/opt/aktin/call-flare.sh}
      PROCESS_ARGS: ${PROCESS_ARGS:-10}
      FLARE_BASE_URL: ${FLARE_BASE_URL:-http://node-flare:5000}
      PROCESS_EXECUTOR_THREADS: ${PROCESS_EXECUTOR_THREADS:-1}
      CQL_FHIR_BASE_URL: ${CQL_FHIR_BASE_URL}
      CQL_FHIR_USER: ${CQL_FHIR_USER}
      CQL_FHIR_PW: ${CQL_FHIR_PW}
      FLARE_URL: ${FLARE_URL}
      FLARE_USER: ${FLARE_USER}
      FLARE_PW: ${FLARE_PW}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_LEVEL_FEASIBILITY: ${LOG_LEVEL_FEASIBILITY:-FINE}
